services:
    # TAMBAHAN BARU: AGAR BISA INSTALL LARAVEL
    app:
        image: webdevops/php-apache:8.2
        container_name: dpc_app
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - "8000:80"
        links:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db_sistem_dpc
            DB_USERNAME: root
            DB_PASSWORD: root_password
            PHP_DATE_TIMEZONE: Asia/Jakarta
            WEB_DOCUMENT_ROOT: /app/public

    # 1. The Database Service
    db:
        image: mysql:8.0
        container_name: dpc_database
        restart: always
        environment:
            MYSQL_DATABASE: db_sistem_dpc
            MYSQL_ROOT_PASSWORD: root_password # You can change this
        ports:
            - "3307:3306" # Maps Local Port 3307 -> Container Port 3306
        volumes:
            - db_data:/var/lib/mysql # Persists data even if container stops
            - ./db_init:/docker-entrypoint-initdb.d # Loads your SQL script automatically!
        command: --default-authentication-plugin=mysql_native_password

    # 2. phpMyAdmin (Optional - for easy viewing)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dpc_pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "8080:80"

volumes:
    db_data:
